#[
autogenerated by docgen
loc: /home/runner/work/fusion/fusion/fusion/src/fusion/js/jsxmlserializer.nim(16, 1)
rdoccmd: 
]#
import "/home/runner/work/fusion/fusion/fusion/src/fusion/js/jsxmlserializer.nim"
from std/dom import document
if defined(fusionJsXMLSerializerTests):
  let cerealizer: XMLSerializer = newXMLSerializer()
  echo cerealizer.serializeToString(node = document)
